title: Steven Jerjian
author: Steven Jerjian
description:
show_downloads: false

theme: jekyll-theme-cayman

navbar-links:
  About: "index"
  Research: "research"
  Portfolio: "portfolio"
  Posts: "posts"
  cv: "assets/pdf/jerjian-resume-2025.pdf"

# Personalize the colours in your website. Colour values can be any valid CSS colour

# navbar-col: "#EAEAEA"
# navbar-text-col: "#404040"
# navbar-border-col: "#DDDDDD"
# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#008AFF"
# hover-col: "#0085A1"
# footer-col: "#EAEAEA"
# footer-text-col: "#777777"
# footer-link-col: "#404040"
# footer-hover-col: "#0085A1"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

social-network-links:
  email: "steven.jerjian@gmail.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
#  facebook: 
  github: sjjerjian
  linkedin: stevenjerjian
  
# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
